### ISSUE TITLE
de_DE

### ISSUE THREAD

**Issue by mmf431** [debiki/ty-cla#3]
In de_DE AllCats: "Alle Kategorien"   (not  AllCats: "Allen Kategorien")

**Comment by kajmagnus** [comment]
Sorry didn't notice, maybe I'm not subscribed to notifications in this repo. I'll fix

Maybe the person who translated, had in mind something like " *In* All Categories" which would be "In Allen Kategorien", right. But you're right that it should be "Alle Kategorien" (there's no "in" before).

**Comment by kajmagnus** [comment]
There was an "in" before "all cats" before, but not any longer

**Comment by kajmagnus** [comment]
I think

**Comment by kajmagnus** [comment]
Fixed in the next version. Closing this then

**Comment by mmf431** [comment]
Thank you very much, Kaj. Best regards. Martin

KajMagnus ***@***.***> schrieb am Mi., 18. Aug. 2021, 07:11:
